# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencvtest/contours.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import opencvtest.msg

class contours(genpy.Message):
  _md5sum = "80338e53bc763a94f85a1a487d6d2c70"
  _type = "opencvtest/contours"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """img_pro_info pro_info
================================================================================
MSG: opencvtest/img_pro_info
    bool find_obs_flag
    float64 dis
    int32 pos_left
    int32 pos_right
    int32 x_pos
    int32 y_pos"""
  __slots__ = ['pro_info']
  _slot_types = ['opencvtest/img_pro_info']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pro_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(contours, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pro_info is None:
        self.pro_info = opencvtest.msg.img_pro_info()
    else:
      self.pro_info = opencvtest.msg.img_pro_info()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bd4i().pack(_x.pro_info.find_obs_flag, _x.pro_info.dis, _x.pro_info.pos_left, _x.pro_info.pos_right, _x.pro_info.x_pos, _x.pro_info.y_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pro_info is None:
        self.pro_info = opencvtest.msg.img_pro_info()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.pro_info.find_obs_flag, _x.pro_info.dis, _x.pro_info.pos_left, _x.pro_info.pos_right, _x.pro_info.x_pos, _x.pro_info.y_pos,) = _get_struct_Bd4i().unpack(str[start:end])
      self.pro_info.find_obs_flag = bool(self.pro_info.find_obs_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bd4i().pack(_x.pro_info.find_obs_flag, _x.pro_info.dis, _x.pro_info.pos_left, _x.pro_info.pos_right, _x.pro_info.x_pos, _x.pro_info.y_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pro_info is None:
        self.pro_info = opencvtest.msg.img_pro_info()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.pro_info.find_obs_flag, _x.pro_info.dis, _x.pro_info.pos_left, _x.pro_info.pos_right, _x.pro_info.x_pos, _x.pro_info.y_pos,) = _get_struct_Bd4i().unpack(str[start:end])
      self.pro_info.find_obs_flag = bool(self.pro_info.find_obs_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bd4i = None
def _get_struct_Bd4i():
    global _struct_Bd4i
    if _struct_Bd4i is None:
        _struct_Bd4i = struct.Struct("<Bd4i")
    return _struct_Bd4i
