// Generated by gencpp from file opencvtest/contours.msg
// DO NOT EDIT!


#ifndef OPENCVTEST_MESSAGE_CONTOURS_H
#define OPENCVTEST_MESSAGE_CONTOURS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <opencvtest/img_pro_info.h>

namespace opencvtest
{
template <class ContainerAllocator>
struct contours_
{
  typedef contours_<ContainerAllocator> Type;

  contours_()
    : pro_info()  {
    }
  contours_(const ContainerAllocator& _alloc)
    : pro_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::opencvtest::img_pro_info_<ContainerAllocator>  _pro_info_type;
  _pro_info_type pro_info;





  typedef boost::shared_ptr< ::opencvtest::contours_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencvtest::contours_<ContainerAllocator> const> ConstPtr;

}; // struct contours_

typedef ::opencvtest::contours_<std::allocator<void> > contours;

typedef boost::shared_ptr< ::opencvtest::contours > contoursPtr;
typedef boost::shared_ptr< ::opencvtest::contours const> contoursConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencvtest::contours_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencvtest::contours_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opencvtest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opencvtest': ['/home/dqn/drone_formation/src/opencvtest/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opencvtest::contours_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencvtest::contours_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencvtest::contours_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencvtest::contours_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencvtest::contours_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencvtest::contours_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencvtest::contours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80338e53bc763a94f85a1a487d6d2c70";
  }

  static const char* value(const ::opencvtest::contours_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80338e53bc763a94ULL;
  static const uint64_t static_value2 = 0xf85a1a487d6d2c70ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencvtest::contours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencvtest/contours";
  }

  static const char* value(const ::opencvtest::contours_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencvtest::contours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "img_pro_info pro_info\n\
================================================================================\n\
MSG: opencvtest/img_pro_info\n\
    bool find_obs_flag\n\
    float64 dis\n\
    int32 pos_left\n\
    int32 pos_right\n\
    int32 x_pos\n\
    int32 y_pos\n\
";
  }

  static const char* value(const ::opencvtest::contours_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencvtest::contours_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pro_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct contours_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencvtest::contours_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencvtest::contours_<ContainerAllocator>& v)
  {
    s << indent << "pro_info: ";
    s << std::endl;
    Printer< ::opencvtest::img_pro_info_<ContainerAllocator> >::stream(s, indent + "  ", v.pro_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCVTEST_MESSAGE_CONTOURS_H
